In [5]:
import pandas as pd

from src.common import get_df_from_excel
from src.club import dir_item, dir_proj, dir_tableau
from src.club import file_excels, file_tsvs
from src.club import convert_excel_to_tsv


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
# def convert_excel_to_tsv(path_dir, file_excel, file_tsv):
#     df = get_df_from_excel(path_dir + file_excel)
#     df.to_csv(path_dir + file_tsv, sep='\t', index=False)

# def add_gu_and_export(file_path, ):
#     def get_gu_from_row(row):
#         for gu in SEOUL_GU:
#             if (gu in row['소재지전체주소']) or (gu in row['도로명전체주소']):
#                 return gu
#         else:
#             return ''
#     df['소재지전체주소'].fillna('', inplace=True)
#     df['도로명전체주소'].fillna('', inplace=True)
#     df['자치구'] = df.apply(get_gu_from_row, axis=1)
#     df.head()
#     df.to_csv(file_path, sep='\t', index=False)

# def export_big_three_gu(path_dir, file_name_ext):
#     import os
#     file_name, file_ext = os.path.splitext(file_name_ext)
#     df = pd.read_csv(path_dir + file_name_ext, sep='\t')
#     df = df.loc[df['자치구'].isin(['강남구', '마포구', '용산구'])]
#     df.to_csv(path_dir + file_name + '_big_three_gu' + file_ext, sep='\t', index=False)

In [4]:
file_index = 2
file_excel = file_excels[file_index]
file_tsv = file_tsvs[file_index]


convert_excel_to_tsv(dir_proj, file_excel, file_tsv)

In [6]:
df = get_df_from_excel(dir_proj + file_excel)
df.head()

,번호,개방서비스명,개방서비스ID,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,1,휴게음식점,07_24_05_P,3000000,3000000-104-1998-09983,19980615,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,64.52,NaN,NaN,NaN
1,2,휴게음식점,07_24_05_P,3000000,3000000-104-1998-09984,19980615,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,38.00,NaN,NaN,NaN
2,3,휴게음식점,07_24_05_P,3000000,3000000-104-1998-08873,19980626,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,74.12,NaN,NaN,NaN
3,4,휴게음식점,07_24_05_P,3000000,3000000-104-1998-08933,19980701,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,31.32,NaN,NaN,NaN
4,5,휴게음식점,07_24_05_P,3000000,3000000-104-2003-00032,20030425,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,20.10,NaN,NaN,NaN

In [10]:
df.head(100)

,번호,개방서비스명,개방서비스ID,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,1,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08338,19741023,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,241.80,NaN,NaN,NaN
1,2,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08313,19740625,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,76.24,NaN,NaN,NaN
2,3,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08323,19740607,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,350.08,NaN,NaN,NaN
3,4,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08231,19740530,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,194.97,NaN,NaN,NaN
4,5,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08292,19740510,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,121.93,NaN,NaN,NaN
5,6,유흥주점영업,07_23_02_P,3000000,3000000-102-1999-11779,19991218,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,58.78,NaN,NaN,NaN
6,7,유흥주점영업,07_23_02_P,3000000,3000000-102-1999-10964,19991218,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,133.26,NaN,NaN,NaN
7,8,유흥주점영업,07_23_02_P,3000000,3000000-102-1985-08261,19850122,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,112.60,NaN,NaN,NaN
8,9,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08276,19841006,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,107.52,NaN,NaN,NaN
9,10,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08322,19840921,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,56.00,NaN,NaN,NaN
10,11,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-11439,19840908,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,67.75,NaN,NaN,NaN
11,12,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08265,19840908,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,114.34,NaN,NaN,NaN
12,13,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08255,19840811,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,336.44,NaN,NaN,NaN
13,14,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08318,19840802,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,129.79,NaN,NaN,NaN
14,15,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08344,19840623,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,69.60,NaN,NaN,NaN
15,16,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08314,19840605,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,73.17,NaN,NaN,NaN
16,17,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08309,19840530,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,99.39,NaN,NaN,NaN
17,18,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08268,19840529,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,145.14,NaN,NaN,NaN
18,19,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08324,19840522,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,73.26,NaN,NaN,NaN
19,20,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-11440,19840522,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,35.25,NaN,NaN,NaN
20,21,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08343,19840521,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,85.76,NaN,NaN,NaN
21,22,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08245,19840327,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,103.34,NaN,NaN,NaN
22,23,유흥주점영업,07_23_02_P,3000000,3000000-102-1984-08262,19840327,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,114.26,NaN,NaN,NaN
23,24,유흥주점영업,07_23_02_P,3000000,3000000-102-2004-00006,20040420,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,89.42,NaN,NaN,NaN
24,25,유흥주점영업,07_23_02_P,3000000,3000000-102-2003-00007,20030612,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,84.32,NaN,NaN,NaN
25,26,유흥주점영업,07_23_02_P,3000000,3000000-102-2001-12247,20010410,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,79.82,NaN,NaN,NaN
26,27,유흥주점영업,07_23_02_P,3000000,3000000-102-2000-11402,20000711,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,71.51,NaN,NaN,NaN
27,28,유흥주점영업,07_23_02_P,3000000,3000000-102-1985-08244,19850305,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,314.23,NaN,NaN,NaN
28,29,유흥주점영업,07_23_02_P,3000000,3000000-102-2000-11330,20000609,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,95.70,NaN,NaN,NaN
29,30,유흥주점영업,07_23_02_P,3000000,3000000-102-1976-08316,19760325,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,176.76,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,유흥주점영업,07_23_02_P,3000000,3000000-102-2000-11650,20001127,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,1497.82,NaN,NaN,NaN
71,72,유흥주점영업,07_23_02_P,3000000,3000000-102-2000-11613,20001117,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,19.14,NaN,NaN,NaN
72,73,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08223,19740430,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,1146.06,NaN,NaN,NaN
73,74,유흥주점영업,07_23_02_P,3000000,3000000-102-1974-08229,19740430,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,95.72,NaN,NaN,NaN
74,75,유흥주점영업,07_23_02_P,3000000,3000000-102-1992-08286,19921228,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,161.62,NaN,NaN,NaN
75,76,유흥주점영업,07_23_02_P,3000000,3000000-102-1992-08304,19921123,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,412.92,NaN,NaN,NaN
76,77,유흥주점영업,07_23_02_P,3000000,3000000-102-1991-08337,19911019,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,90.00,NaN,NaN,NaN
77,78,유흥주점영업,07_23_02_P,3000000,3000000-102-1991-08249,19910305,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,77.94,NaN,NaN,NaN
78,79,유흥주점영업,07_23_02_P,3000000,3000000-102-1990-08274,19901211,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,97.60,NaN,NaN,NaN
79,80,유흥주점영업,07_23_02_P,3000000,3000000-102-1990-08289,19901031,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,125.00,NaN,NaN,NaN
80,81,유흥주점영업,07_23_02_P,3000000,3000000-102-1990-08272,19900412,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,81.40,NaN,NaN,NaN
81,82,유흥주점영업,07_23_02_P,3000000,3000000-102-1989-08279,19891027,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,90.80,NaN,NaN,NaN
82,83,유흥주점영업,07_23_02_P,3000000,3000000-102-1986-08251,19860502,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,184.45,NaN,NaN,NaN
83,84,유흥주점영업,07_23_02_P,3000000,3000000-102-1986-08242,19860129,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,86.87,NaN,NaN,NaN
84,85,유흥주점영업,07_23_02_P,3000000,3000000-102-1985-08282,19850828,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,78.76,NaN,NaN,NaN
85,86,유흥주점영업,07_23_02_P,3000000,3000000-102-2014-00001,20140421,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,Y,17.11,NaN,NaN,NaN
86,87,유흥주점영업,07_23_02_P,3000000,3000000-102-2013-00006,20130725,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,Y,92.19,NaN,NaN,NaN
87,88,유흥주점영업,07_23_02_P,3000000,3000000-102-2013-00005,20130607,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,130.14,NaN,NaN,NaN
88,89,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08333,19751220,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,120.56,NaN,NaN,NaN
89,90,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08311,19751216,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,333.06,NaN,NaN,NaN
90,91,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08288,19751216,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,517.68,NaN,NaN,NaN
91,92,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08228,19751216,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,376.50,NaN,NaN,NaN
92,93,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08236,19751002,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,461.90,NaN,NaN,NaN
93,94,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08327,19751001,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,616.56,NaN,NaN,NaN
94,95,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08329,19750813,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,145.70,NaN,NaN,NaN
95,96,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08283,19750626,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,67.32,NaN,NaN,NaN
96,97,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08235,19750528,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,436.66,NaN,NaN,NaN
97,98,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08310,19750423,NaN,1,영업/정상,1,...,NaN,NaN,NaN,NaN,NaN,N,120.75,NaN,NaN,NaN
98,99,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08300,19750302,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,4.50,NaN,NaN,NaN
99,100,유흥주점영업,07_23_02_P,3000000,3000000-102-1975-08234,19750122,NaN,3,폐업,2,...,NaN,NaN,NaN,NaN,NaN,N,448.20,NaN,NaN,NaN