In [2]:
import pandas as pd

from src.common import eprint
from src.common import SEOUL_GU
from src.common import get_df_from_excel
from src.club import dir_item, dir_proj, dir_tableau
from src.club import file_excels, file_tsvs, file_gu
from src.club import convert_excel_to_tsv
from src.club import add_gu_and_export
import src.mongos as mg

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_columns', None)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
idx = 2
df = pd.read_csv(dir_proj + file_gu[idx], sep='\t')
print(df.shape)
df.head()

(18461, 48)

/home/jake/.virtualenvs/workspace/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,번호,개방서비스명,개방서비스ID,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,휴업종료일자,재개업일자,소재지전화,소재지면적,소재지우편번호,소재지전체주소,도로명전체주소,도로명우편번호,사업장명,최종수정시점,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),위생업태명,남성종사자수,여성종사자수,영업장주변구분명,등급구분명,급수시설구분명,총종업원수,본사종업원수,공장사무직종업원수,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지,자치구
0,10566,휴게음식점,07_24_05_P,3020000,3020000-104-1981-02696,19811116,NaN,3,폐업,2,폐업,19930515.0,NaN,NaN,NaN,02 7957771,54.82,140823.0,서울특별시 용산구 보광동 217-31번지,NaN,NaN,호수,20010927000000,I,2018-08-31 23:59:59.0,다방,199964.476635,447115.813892,다방,0.0,2.0,기타,지도,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,54.82,NaN,NaN,NaN,용산구
1,10567,휴게음식점,07_24_05_P,3020000,3020000-104-1985-03060,19850821,NaN,3,폐업,2,폐업,19881223.0,NaN,NaN,NaN,0207174100,30.40,140875.0,서울특별시 용산구 한강로2가 215-2번지,NaN,NaN,멕스컨햄버거용사,20010927000000,I,2018-08-31 23:59:59.0,과자점,196900.086208,447132.311494,과자점,1.0,1.0,기타,지도,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,30.40,NaN,NaN,NaN,용산구
2,10568,휴게음식점,07_24_05_P,3020000,3020000-104-1986-02627,19860407,NaN,3,폐업,2,폐업,19940810.0,NaN,NaN,NaN,0207144679,134.80,140807.0,서울특별시 용산구 갈월동 87-2번지,NaN,NaN,노블레스,20010927000000,I,2018-08-31 23:59:59.0,다방,197443.565756,449070.316620,다방,1.0,2.0,유흥업소밀집지역,지도,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,134.80,NaN,NaN,NaN,용산구
3,10569,휴게음식점,07_24_05_P,3020000,3020000-104-1992-02790,19920515,NaN,3,폐업,2,폐업,20030226.0,NaN,NaN,NaN,0207493490,100.97,140886.0,서울특별시 용산구 한남동 76-41번지,NaN,NaN,쟈뎅,20010927000000,I,2018-08-31 23:59:59.0,다방,200506.690815,447956.137926,다방,0.0,0.0,기타,기타,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,100.97,NaN,NaN,NaN,용산구
4,10570,휴게음식점,07_24_05_P,3020000,3020000-104-1975-02893,19751201,NaN,3,폐업,2,폐업,19920922.0,NaN,NaN,NaN,0207946778,105.60,140807.0,서울특별시 용산구 갈월동 98-47번지,NaN,NaN,남영,20010927000000,I,2018-08-31 23:59:59.0,다방,197409.420047,448819.911638,다방,0.0,1.0,유흥업소밀집지역,지도,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,105.60,NaN,NaN,NaN,용산구

In [5]:
df2 = df.loc[df['영업상태명']=='영업/정상']
print(len(df2))
df2.head()

6382

,번호,개방서비스명,개방서비스ID,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,휴업종료일자,재개업일자,소재지전화,소재지면적,소재지우편번호,소재지전체주소,도로명전체주소,도로명우편번호,사업장명,최종수정시점,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),위생업태명,남성종사자수,여성종사자수,영업장주변구분명,등급구분명,급수시설구분명,총종업원수,본사종업원수,공장사무직종업원수,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지,자치구
1707,12273,휴게음식점,07_24_05_P,3020000,3020000-104-2018-00092,20180823,NaN,1,영업/정상,1,영업,NaN,NaN,NaN,NaN,NaN,16.77,140861.0,서울특별시 용산구 이태원동 313-1번지 1층,"서울특별시 용산구 녹사평대로46길 46, 1층 (이태원동)",4345.0,쥬스오피스,20180823131256,I,2018-08-31 23:59:59.0,기타 휴게음식점,198960.478098,448402.501610,기타 휴게음식점,NaN,NaN,NaN,NaN,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,16.77,NaN,NaN,NaN,용산구
1708,12274,휴게음식점,07_24_05_P,3020000,3020000-104-2018-00093,20180824,NaN,1,영업/정상,1,영업,NaN,NaN,NaN,NaN,NaN,51.71,140011.0,서울특별시 용산구 한강로1가 64번지 대우 월드마크 용산 107호,"서울특별시 용산구 한강대로 211, 1층 107호 (한강로1가, 대우 월드마크 용산)",4322.0,카페서울,20181226103500,U,2018-12-28 02:40:00.0,커피숍,197542.687282,448325.294355,커피숍,NaN,NaN,NaN,NaN,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,51.71,NaN,NaN,NaN,용산구
1709,12275,휴게음식점,07_24_05_P,3020000,3020000-104-2018-00094,20180827,NaN,1,영업/정상,1,영업,NaN,NaN,NaN,NaN,NaN,6.60,140893.0,서울특별시 용산구 한남동 737-4번지 1층,"서울특별시 용산구 이태원로 227, 1층 (한남동)",4349.0,이마트24이태원제일점,20180827144829,I,2018-08-31 23:59:59.0,기타 휴게음식점,199826.532795,448157.316168,기타 휴게음식점,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,6.60,NaN,NaN,NaN,용산구
1710,12276,휴게음식점,07_24_05_P,3020000,3020000-104-2018-00095,20180831,NaN,1,영업/정상,1,영업,NaN,NaN,NaN,NaN,NaN,86.29,140133.0,"서울특별시 용산구 청파동3가 109-12번지 지하1층, 지상1,2층","서울특별시 용산구 청파로47길 37-22, 지하1, 지상1,2층 (청파동3가)",4313.0,레드우드(Redwood),20180831142716,I,2018-08-31 23:59:59.0,커피숍,197097.386769,449111.355278,커피숍,NaN,NaN,NaN,NaN,상수도전용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,86.29,NaN,NaN,NaN,용산구
1711,12277,휴게음식점,07_24_05_P,3020000,3020000-104-2002-00040,20020827,NaN,1,영업/정상,1,영업,NaN,NaN,NaN,NaN,NaN,26.40,140133.0,서울특별시 용산구 청파동3가 24-13번지,서울특별시 용산구 청파로45길 10 (청파동3가),4313.0,뽀빠,20020827000000,I,2018-08-31 23:59:59.0,기타 휴게음식점,197285.182544,449123.432214,기타 휴게음식점,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,26.40,NaN,NaN,NaN,용산구

In [6]:
mg.to_mongo(df2, 'club', 'rest', delete=True)

Deleted rows: 0
Inserted rows: 6382